"""
booth_demographics.py
---------------------
Reads voter.json and computes per-booth demographic profiles for the
WhatsApp Volunteer Assistant LLM.
"""

import json
import os
import logging
from functools import lru_cache
from typing import Optional

logger = logging.getLogger(__name__)

# Path to the voter data (generated by the Boothman seeder)
# From: backend/app/domain/services/  → go up 4 levels to project root → frontend/prisma/voter.json
_SERVICES_DIR = os.path.dirname(os.path.abspath(__file__))
VOTER_JSON_PATH = os.path.normpath(
    os.path.join(_SERVICES_DIR, "..", "..", "..", "..", "frontend", "prisma", "voter.json")
)


def _load_voters() -> list:
    """Load all voters from voter.json. Cached after first call."""
    try:
        with open(VOTER_JSON_PATH, "r") as f:
            return json.load(f)
    except Exception as e:
        logger.error(f"Failed to load voter.json from {VOTER_JSON_PATH}: {e}")
        return []


# Cache the loaded data in memory
_voter_cache: Optional[list] = None


def _get_voters() -> list:
    global _voter_cache
    if _voter_cache is None:
        _voter_cache = _load_voters()
    return _voter_cache


def _extract_surname(full_name: str) -> str:
    """Extract the last word of a name as the surname."""
    parts = full_name.strip().split()
    return parts[-1] if parts else ""


def get_booth_profile(part_number: str) -> dict:
    """
    Compute a demographic profile for a given booth (by part_number).
    
    Returns a dict with:
      - total_voters
      - gender breakdown
      - age group breakdown
      - top surnames (up to 10)
      - sections
      - percentage calculations
    """
    voters = _get_voters()
    booth_voters = [v for v in voters if v.get("part_number") == part_number]

    if not booth_voters:
        return {
            "part_number": part_number,
            "total_voters": 0,
            "gender": {},
            "age_groups": {},
            "top_surnames": [],
            "sections": [],
            "female_percentage": 0,
            "youth_percentage": 0,
            "senior_percentage": 0,
        }

    total = len(booth_voters)

    # Gender
    gender = {}
    for v in booth_voters:
        g = v.get("gender", "Unknown")
        gender[g] = gender.get(g, 0) + 1

    # Age groups
    youth = sum(1 for v in booth_voters if v.get("age", 0) < 30)
    middle = sum(1 for v in booth_voters if 30 <= v.get("age", 0) < 50)
    senior = sum(1 for v in booth_voters if v.get("age", 0) >= 50)

    # Surnames
    surname_freq = {}
    for v in booth_voters:
        surname = _extract_surname(v.get("name", ""))
        if surname:
            surname_freq[surname] = surname_freq.get(surname, 0) + 1
    top_surnames = sorted(surname_freq.items(), key=lambda x: x[1], reverse=True)[:10]

    # Sections
    sections = list(set(v.get("section", "") for v in booth_voters if v.get("section")))

    female_count = gender.get("Female", 0)

    return {
        "part_number": part_number,
        "total_voters": total,
        "gender": gender,
        "age_groups": {
            "Youth (below 30)": youth,
            "Middle-aged (30-50)": middle,
            "Senior (above 50)": senior,
        },
        "top_surnames": top_surnames,
        "sections": sections,
        "female_percentage": round(female_count * 100 / total, 1) if total else 0,
        "youth_percentage": round(youth * 100 / total, 1) if total else 0,
        "senior_percentage": round(senior * 100 / total, 1) if total else 0,
    }


def get_matching_voters(part_number: str, volunteer_surname: str) -> list:
    """
    Find voters in the booth whose surname matches the volunteer's surname.
    Returns a list of dicts with voter details (name, house_no, age, gender).
    """
    if not volunteer_surname:
        return []

    voters = _get_voters()
    surname_lower = volunteer_surname.lower()

    matches = []
    for v in voters:
        if v.get("part_number") != part_number:
            continue
        voter_surname = _extract_surname(v.get("name", "")).lower()
        if voter_surname == surname_lower:
            matches.append({
                "name": v.get("name"),
                "house_no": v.get("house_no"),
                "age": v.get("age"),
                "gender": v.get("gender"),
            })

    return matches


def format_profile_for_prompt(profile: dict, matching_voters: list, volunteer_surname: str) -> str:
    """
    Format the booth profile and matched voters into a concise text block
    suitable for injection into an LLM prompt.
    """
    lines = []
    lines.append(f"BOOTH: {profile['part_number']}")
    lines.append(f"Total Voters: {profile['total_voters']}")

    # Gender
    gender_parts = [f"{k}: {v}" for k, v in profile["gender"].items()]
    lines.append(f"Gender: {', '.join(gender_parts)} ({profile['female_percentage']}% female)")

    # Age
    age_parts = [f"{k}: {v}" for k, v in profile["age_groups"].items()]
    lines.append(f"Age Groups: {', '.join(age_parts)}")
    lines.append(f"  Youth %: {profile['youth_percentage']}%, Senior %: {profile['senior_percentage']}%")

    # Top communities
    if profile["top_surnames"]:
        surname_parts = [f"{s} ({c})" for s, c in profile["top_surnames"]]
        lines.append(f"Top Surnames/Communities: {', '.join(surname_parts)}")

    # Sections
    if profile["sections"]:
        lines.append(f"Sections/Localities: {', '.join(profile['sections'])}")

    # Matched voters
    if matching_voters:
        lines.append(f"\nCASTE-MATCHED VOTERS (surname '{volunteer_surname}' — {len(matching_voters)} voters):")
        # Group by house
        house_groups = {}
        for mv in matching_voters:
            h = mv["house_no"]
            if h not in house_groups:
                house_groups[h] = []
            house_groups[h].append(mv)
        for house, members in list(house_groups.items())[:15]:  # limit to 15 houses
            names = ", ".join(f"{m['name']} (age {m['age']}, {m['gender']})" for m in members)
            lines.append(f"  House {house}: {names}")
    else:
        lines.append(f"\nNo caste-matched voters found for surname '{volunteer_surname}' in this booth.")

    return "\n".join(lines)
